# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b32cee15225debfd299c704420b87b2d53cf1133581649e276a378ef0fcce152b27d1ed6c05a9678e925444c49a9e7bd4884a257e43a804cded9403a91e3225

test:
  secret_key_base: 7fc5890fd3dfe1eef992a4bff43ab185b8e1c2bf26ea55b6733818f71a9886419ba7b6cf86df759b44f72ec910193d0c81d19b91db924d5c310a427271576742

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
